# Generated by Django 3.2.4 on 2021-06-26 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Doujinshi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhentai_id', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('subtitle', models.CharField(max_length=256)),
                ('upload_date', models.DateTimeField()),
                ('URL', models.CharField(max_length=256)),
                ('Pages', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webmnhentai.category')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Parody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doujinshi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmnhentai.doujinshi')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webmnhentai.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Parodys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doujinshi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmnhentai.doujinshi')),
                ('parody_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webmnhentai.parody')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doujinshi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmnhentai.doujinshi')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webmnhentai.group')),
            ],
        ),
        migrations.AddField(
            model_name='doujinshi',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webmnhentai.language'),
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webmnhentai.character')),
                ('doujinshi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmnhentai.doujinshi')),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webmnhentai.artist')),
                ('doujinshi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmnhentai.doujinshi')),
            ],
        ),
    ]
