# Generated by Django 3.2.4 on 2021-06-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmnhentai', '0003_auto_20210627_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parody',
            old_name='title',
            new_name='name',
        ),
    ]
